name: "reviewing-code"
version: "1.1.0"
model: "sonnet"
color: "purple"

# v1.14.0: Skill best practices (Issue #97)
effort_hint: medium
danger_level: moderate
categories:
  - quality

description: |
  Use this skill IF sprint implementation needs review, validation, and quality
  gate approval. Reviews code quality, security, testing, and architecture alignment.
  Either approves (writes "All good") OR provides detailed feedback. Produces
  feedback at grimoires/loa/a2a/sprint-N/engineer-feedback.md.

triggers:
  - "/review-sprint"
  - "review sprint implementation"
  - "validate sprint"
  - "check sprint quality"
  - "review the implementation"
  - "is sprint complete"

examples:
  - context: "Engineer has completed sprint implementation and generated a report"
    user_says: "Review the sprint 1 implementation"
    agent_action: "Launch reviewing-code to review implementation, validate against acceptance criteria, and provide feedback"
  - context: "Engineer has addressed previous feedback"
    user_says: "The engineer has fixed the issues, please review again"
    agent_action: "Launch reviewing-code to verify all feedback has been properly addressed"
  - context: "User wants to check sprint progress and code quality"
    user_says: "Check if sprint 2 is complete and meets our quality standards"
    agent_action: "Launch reviewing-code to review sprint 2 completeness and quality"

dependencies:
  - skill: "implementing-tasks"
    artifact: "grimoires/loa/a2a/sprint-N/reviewer.md"

inputs:
  - name: "sprint_id"
    type: "string"
    pattern: "^sprint-[0-9]+$"
    required: true
    description: "Sprint identifier (e.g., sprint-1)"

# v1.14.0: Native Anthropic input examples
inputExamples:
  - input:
      sprint_id: "sprint-1"
    description: "Review first sprint after implementation"
  - input:
      sprint_id: "sprint-3"
    description: "Review sprint after feedback addressed"

outputs:
  - path: "grimoires/loa/a2a/sprint-{id}/engineer-feedback.md"
    description: "Review feedback for engineer (or 'All good' if approved)"
    format: detailed

# v0.9.0 Lossless Ledger Protocol Integration
protocols:
  required:
    - name: "session-continuity"
      path: ".claude/protocols/session-continuity.md"
      purpose: "Session lifecycle, tiered recovery"
    - name: "grounding-enforcement"
      path: ".claude/protocols/grounding-enforcement.md"
      purpose: "Verify implementation citations, check grounding ratio"
  recommended:
    - name: "jit-retrieval"
      path: ".claude/protocols/jit-retrieval.md"
      purpose: "Lightweight identifiers for code review"

# Review includes grounding verification
review_checklist:
  - "Code quality and patterns"
  - "Security considerations"
  - "Test coverage"
  - "Grounding ratio >= 0.95 in implementation report"
  - "Citations use ${PROJECT_ROOT} absolute paths"
